/*
 * This file is generated by jOOQ.
 */
package kiinse.plugin.thirstforwater.data.thirst.sql.database;


import kiinse.plugin.thirstforwater.data.thirst.sql.database.tables.Players;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.players</code>.
     */
    public static final Players PLAYERS = Players.PLAYERS;
}
